-- Migration 014: Create civic alerts and advisories system
-- CivicWatch AI Kenya — Milestone 11: Civic Alerts & Advisories

-- 1. Create civic_alerts table
CREATE TABLE IF NOT EXISTS civic_alerts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  summary VARCHAR(500) NOT NULL,
  description TEXT NOT NULL,
  alert_type ENUM(
    'OFFICIAL_COUNTY_ALERT',
    'GOVERNMENT_ADVISORY',
    'UTILITY_DOWNTIME',
    'PUBLIC_SAFETY',
    'WEATHER_ENVIRONMENTAL',
    'COMMUNITY_ADVISORY'
  ) NOT NULL,
  severity ENUM('INFO', 'LOW', 'MODERATE', 'HIGH', 'CRITICAL') NOT NULL DEFAULT 'INFO',
  status ENUM(
    'DRAFT',
    'PENDING_REVIEW',
    'ACTIVE',
    'SCHEDULED',
    'EXPIRED',
    'CANCELLED',
    'ARCHIVED'
  ) NOT NULL DEFAULT 'DRAFT',
  verification_status ENUM('PENDING', 'VERIFIED', 'REJECTED', 'EXPIRED') NOT NULL DEFAULT 'PENDING',
  is_official BOOLEAN NOT NULL DEFAULT FALSE,
  source_type ENUM(
    'COUNTY_GOVERNMENT',
    'NATIONAL_AGENCY',
    'UTILITY_PROVIDER',
    'EMERGENCY_SERVICES',
    'CIVIC_ORGANIZATION',
    'COMMUNITY'
  ) NOT NULL DEFAULT 'COMMUNITY',
  source_name VARCHAR(255) NOT NULL,
  source_reference VARCHAR(500) NULL,
  county VARCHAR(100) NULL,
  sub_county VARCHAR(100) NULL,
  ward VARCHAR(100) NULL,
  location_text VARCHAR(255) NULL,
  utility_service ENUM(
    'ELECTRICITY',
    'WATER',
    'ROAD_INFRASTRUCTURE',
    'WASTE_SANITATION',
    'INTERNET_TELECOM',
    'OTHER'
  ) NULL,
  downtime_status ENUM('PLANNED', 'ONGOING', 'RESTORED', 'CANCELLED') NULL,
  expected_restoration TIMESTAMP NULL,
  actual_restoration TIMESTAMP NULL,
  recommended_action TEXT NULL,
  start_time TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  end_time TIMESTAMP NULL,
  published_at TIMESTAMP NULL,
  created_by INT NOT NULL,
  verified_by INT NULL,
  verified_at TIMESTAMP NULL,
  is_public BOOLEAN NOT NULL DEFAULT TRUE,
  is_demo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_civic_alerts_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_civic_alerts_verifier FOREIGN KEY (verified_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_civic_alerts_status (status),
  INDEX idx_civic_alerts_type (alert_type),
  INDEX idx_civic_alerts_severity (severity),
  INDEX idx_civic_alerts_county (county),
  INDEX idx_civic_alerts_published (published_at),
  INDEX idx_civic_alerts_active_window (status, start_time, end_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Create civic_alert_audits table for tracking complete lifecycle history
CREATE TABLE IF NOT EXISTS civic_alert_audits (
  id INT AUTO_INCREMENT PRIMARY KEY,
  alert_id INT NOT NULL,
  user_id INT NOT NULL,
  action VARCHAR(50) NOT NULL,
  change_summary VARCHAR(500) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_alert_audits_alert FOREIGN KEY (alert_id) REFERENCES civic_alerts(id) ON DELETE CASCADE,
  CONSTRAINT fk_alert_audits_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
  INDEX idx_alert_audits_alert (alert_id),
  INDEX idx_alert_audits_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. Seed initial realistic demo alerts with explicit is_demo = TRUE (Rule 35)
INSERT INTO civic_alerts (
  title,
  summary,
  description,
  alert_type,
  severity,
  status,
  verification_status,
  is_official,
  source_type,
  source_name,
  source_reference,
  county,
  sub_county,
  ward,
  location_text,
  utility_service,
  downtime_status,
  expected_restoration,
  recommended_action,
  start_time,
  end_time,
  published_at,
  created_by,
  verified_by,
  verified_at,
  is_public,
  is_demo
) VALUES 
(
  '[DEMO] Scheduled 48-Hour Water Interruption in Westlands & Parklands',
  'Planned shutdown of Sasumua transmission pipeline for emergency valve replacement.',
  'Nairobi City Water and Sewerage Company (NCWSC) wishes to inform consumers in Westlands, Parklands, Kitisuru, and surrounding estates that water supply will be shut down from Friday 06:00 to Sunday 06:00 to facilitate emergency rehabilitation of the main transmission pipeline at Sasumua.\n\nAffected areas include: Westlands, Parklands, Highridge, Kitisuru, Spring Valley, Kangemi, and parts of Lavington.\n\nResidents are strongly advised to store adequate water prior to the shutdown and use reserves sparingly. Water bowsers will be dispatched to referral hospitals and key health facilities.',
  'UTILITY_DOWNTIME',
  'HIGH',
  'ACTIVE',
  'VERIFIED',
  TRUE,
  'UTILITY_PROVIDER',
  'Nairobi City Water & Sewerage Company (NCWSC)',
  'https://nairobiwater.co.ke/notices/sasumua-rehab-2026',
  'Nairobi',
  'Westlands',
  'Parklands/Highridge',
  'Parklands, Westlands, Kitisuru, Highridge',
  'WATER',
  'PLANNED',
  DATE_ADD(NOW(), INTERVAL 2 DAY),
  'Store sufficient clean water for 48 hours for drinking and essential sanitation. Boil or treat drinking water upon initial supply restoration.',
  NOW(),
  DATE_ADD(NOW(), INTERVAL 3 DAY),
  NOW(),
  1,
  1,
  NOW(),
  TRUE,
  TRUE
),
(
  '[DEMO] Heavy Rainfall & Flash Flood Advisory for Coastal Lowlands',
  'Kenya Meteorological Department advisory on active convective storms over Mombasa and Kilifi.',
  'The Kenya Meteorological Department (KMD) has issued a 72-hour severe weather advisory indicating heavy downpours (exceeding 50mm in 24 hours) accompanied by strong gusty winds and high ocean swells across Mombasa, Kilifi, and Kwale coastal lowlands.\n\nRisk of urban flash flooding along low-lying road networks, especially along Nyali, Kisauni, and Likoni drainage corridors. Small craft and sea fishermen are urged to exercise extreme caution.',
  'WEATHER_ENVIRONMENTAL',
  'HIGH',
  'ACTIVE',
  'VERIFIED',
  TRUE,
  'NATIONAL_AGENCY',
  'Kenya Meteorological Department (KMD)',
  'https://meteo.go.ke/advisories/kmd-marine-flood-042',
  'Mombasa',
  'Kisauni',
  'Nyali',
  'Nyali, Bamburi, Likoni, Old Town coastlines',
  NULL,
  NULL,
  NULL,
  'Avoid crossing flooded bridges and submerged culverts. Move valuable assets to higher ground. Fishermen should suspend deep-water boat voyages during peak storm periods.',
  NOW(),
  DATE_ADD(NOW(), INTERVAL 3 DAY),
  NOW(),
  1,
  1,
  NOW(),
  TRUE,
  TRUE
),
(
  '[DEMO] Temporary Road Closure along Argwings Kodhek for Overpass Crane Demounting',
  'KeNHA announces diversion between Chania Avenue and Ring Road Kilimani from midnight to 06:00.',
  'The Kenya National Highways Authority (KeNHA) alerts motorists that a section of Argwings Kodhek Road between Chania Avenue and Ring Road Kilimani will be completely closed tonight between 00:00 and 06:00 to safely demount heavy crawler cranes used in overpass beam installation.\n\nTraffic marshals and police officers will redirect eastbound traffic via Elgeyo Marakwet Road and westbound traffic via Wood Avenue.',
  'PUBLIC_SAFETY',
  'MODERATE',
  'ACTIVE',
  'VERIFIED',
  TRUE,
  'NATIONAL_AGENCY',
  'Kenya National Highways Authority (KeNHA)',
  'https://kenha.co.ke/traffic-advisories/argwings-closure-beam',
  'Nairobi',
  'Dagoretti North',
  'Kilimani',
  'Argwings Kodhek Road between Chania Ave and Ring Road',
  'ROAD_INFRASTRUCTURE',
  'ONGOING',
  DATE_ADD(NOW(), INTERVAL 12 HOUR),
  'Motorists are advised to utilize Elgeyo Marakwet Road or Ngong Road as alternative corridors and observe direction from traffic marshals.',
  NOW(),
  DATE_ADD(NOW(), INTERVAL 1 DAY),
  NOW(),
  1,
  1,
  NOW(),
  TRUE,
  TRUE
),
(
  '[DEMO] Community Advisory: Uncollected Solid Waste near Kangemi Market',
  'Citizen report verified by community monitors regarding garbage accumulation near fresh produce stalls.',
  'Local vendors and community residents report that municipal garbage trucks have not serviced the collection point adjacent to Kangemi Market for six consecutive days following depot mechanical issues, causing severe drainage blockage and odor concerns.\n\nSub-county public health officials have been notified through CivicWatch incident CWK-2026-000004.',
  'COMMUNITY_ADVISORY',
  'LOW',
  'ACTIVE',
  'VERIFIED',
  FALSE,
  'COMMUNITY',
  'Kangemi Community Welfare Monitors',
  NULL,
  'Nairobi',
  'Westlands',
  'Kangemi',
  'Kangemi Market Fresh Produce Wing',
  'WASTE_SANITATION',
  'ONGOING',
  DATE_ADD(NOW(), INTERVAL 24 HOUR),
  'Vendors are advised to bag perishables tightly and avoid dumping waste into open stormwater trenches.',
  NOW(),
  DATE_ADD(NOW(), INTERVAL 4 DAY),
  NOW(),
  1,
  1,
  NOW(),
  TRUE,
  TRUE
);
